name: API Triggered Workflow
 will run
on:
 repository_dispatch:
    types: [on-demand-tes]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
       pr_number: ${{ github.event.client_payload.pr_number}}
       #baselineTag: ${{ github.event.client_payload.baselinetag }}
       #revision_number: ${{ github.event.client_payload.revision_number }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -tal
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $pr_number
