on:
  workflow_call:
    inputs:
      commit_name:
        required: true
        type: string
      commit_hash:
        required: true
        type: string

env:
  PR_REF: ${{ github.ref }}
        
jobs:
  testbuild:
    runs-on: ubuntu-22.04
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "replace"
        run: |
          echo $PR_REF
          ls
          cat meta.yaml
          set 
         
          
# source:
#  git_url: https://github.com/nest/nest-simulator
#  git_ref: tag/v3.1   
